#!/bin/bash

# Stow in usr/local/bin

if [ "$#" -ge 1 ] && ! [ -f "$1" ]; then
    echo "'$1' is not an existing file"
    exit 1
fi

WALLPAPER_DIR="${1:-$HOME/wallpapers/}"

wal -i "$WALLPAPER_DIR" -n --recursive > /dev/null

sleep 0.1
IMAGE_LOCATION=$(< "$HOME/.cache/wal/wal")

osascript << EOF
tell application "System Events"
    -- Get all desktops and set wallpaper
    repeat with currentDesktop in (every desktop)
        set picture of currentDesktop to "$IMAGE_LOCATION"
    end repeat
end tell
EOF

# TMUX
tmux source-file ~/.tmux.conf

# KITTY 
KITTY_SOCKET=$(find /tmp/mykitty-*)
kitty @ --to=unix:$KITTY_SOCKET set-colors --all --configured ~/.cache/wal/colors-kitty.conf

# SKETCHYBAR
source ~/.config/sketchybar/sketchybarrc > /dev/null

# NEOVIM
for NVIM_SOCKET in $(find /tmp/nvim-*.sock);
do
    nvr --servername $NVIM_SOCKET --remote-send ':colorscheme pywal<CR>'
done
