#!/bin/bash

# Stow in usr/local/bin

if [ "$#" -ge 1 ] && ! [ -f "$1" ]; then
    echo "'$1' is not an existing file"
    exit 1
fi

WALLPAPER_DIR="${1:-$HOME/wallpapers/}"

wal -i "$WALLPAPER_DIR" -n --recursive > /dev/null

sleep 0.1
IMAGE_LOCATION=$(< "$HOME/.cache/wal/wal")
wallpaper set $IMAGE_LOCATION --screen all

tmux source-file ~/.tmux.conf

KITTY_SOCKET=$(find /tmp/mykitty-*)
if [ -n "$KITTY_SOCKET" ]; then
    kitty @ --to=unix:$KITTY_SOCKET set-colors --all --configured ~/.cache/wal/colors-kitty.conf
else
    echo "No Kitty socket found"
fi
