WAL_JSON="$HOME/.cache/wal/colors.json"
OBSIDIAN_SNIPPET="$HOME/Documents/Obsidian/My Brain/.obsidian/snippets/pywal.css"

if [ -f "$WAL_JSON" ]; then
    BG=$(jq -r '.special.background' "$WAL_JSON")
    FG=$(jq -r '.special.foreground' "$WAL_JSON")
    ACCENT=$(jq -r '.colors.color4' "$WAL_JSON")


    # Convert accent to HSL (Obsidian likes h/s/l vars)
    read H S L <<< $(osascript -l JavaScript -e "
        function hexToHSL(hex) {
          hex = hex.replace('#','');
          let r = parseInt(hex.substring(0,2),16)/255;
          let g = parseInt(hex.substring(2,4),16)/255;
          let b = parseInt(hex.substring(4,6),16)/255;
          let max = Math.max(r,g,b), min = Math.min(r,g,b);
          let h, s, l = (max+min)/2;
          if(max == min){ h = s = 0; }
          else {
            let d = max-min;
            s = l > 0.5 ? d/(2-max-min) : d/(max+min);
            switch(max){
              case r: h = (g-b)/d + (g<b?6:0); break;
              case g: h = (b-r)/d + 2; break;
              case b: h = (r-g)/d + 4; break;
            }
            h /= 6;
          }
          return [Math.round(h*360), Math.round(s*100)+'%', Math.round(l*100)+'%'];
        }
        hexToHSL('$ACCENT').join(' ')
    ")


cat > "$OBSIDIAN_SNIPPET" <<EOF
/* Generated by pywal integration */
.theme-dark {
  --accent-color: $ACCENT;
  --accent-h: $H;
  --accent-s: $S;
  --accent-l: $L;

  /* Primary backgrounds */
  --background-primary: $BG;
  --background-primary-alt: $(jq -r '.colors.color0' "$WAL_JSON");

  /* Secondary backgrounds */
  --background-secondary: $(jq -r '.colors.color0' "$WAL_JSON");
  --background-secondary-alt: $(jq -r '.colors.color0' "$WAL_JSON");

  /* Borders and modifiers */
  --background-modifier-border: $(jq -r '.colors.color8' "$WAL_JSON");
  --background-modifier-hover: $(jq -r '.colors.color3' "$WAL_JSON");
  --background-modifier-active: $(jq -r '.colors.color4' "$WAL_JSON");

  /* Text */
  --text-normal: $FG;
}
EOF
fi
